### ISSUE TITLE
SlackApiError

### ISSUE THREAD

**Issue by huiji072** [huiji072/AWS-Cloud-Bootcamp#1]
kimhuiji@gimhuijiui-MacBookAir Seek_Crolling % /usr/bin/python3 /Users/kimhuiji/Desktop/Seek_Crolling/seek/crawl/seek_crawl.py

/Users/kimhuiji/Library/Python/3.9/lib/python/site-packages/slack_sdk/web/internal_utils.py:290: UserWarning: The top-level `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message. The `text` argument is used in places where content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
  warnings.warn(missing_text_message, UserWarning)
DEBUG:slack_sdk.web.base_client:Sending a request - url: https://www.slack.com/api/chat.postMessage, query_params: {}, body_params: {}, files: {}, json_body: {'channel': '#seek', 'blocks': [{'type': 'section', 'text': {'type': 'mrkdwn', 'text': ':exclamation:*SEEK 채용 공고*:exclamation:\n*<https://www.seek.com.au/job/59930960?type=promoted>*'}}, {'type': 'section', 'text': {'type': 'mrkdwn', 'text': "*회사명:*\nIRT Group\n*위치:*\nCapalaba, Brisbane QLD\n*직무:*\nWarehousing, Storage & Distribution (Manufacturing, Transport & Logistics)\n*공고날짜:*\n2023-01-30\n*지원서 양식:*\nDo you have experience operating a forklift?\nDo you have a heavy vehicle driver's licence?\nHow many years' experience do you have as a warehouse storeperson?\n"}}]}, headers: {'Content-Type': 'application/json;charset=utf-8', 'Authorization': '(redacted)', 'User-Agent': 'Python/3.9.6 slackclient/3.19.5 Darwin/21.6.0'}
DEBUG:slack_sdk.web.base_client:Received the following response - status: 200, headers: {'date': 'Mon, 30 Jan 2023 08:29:39 GMT', 'server': 'Apache', 'x-powered-by': 'HHVM/4.153.1', 'access-control-allow-origin': '*', 'referrer-policy': 'no-referrer', 'x-slack-backend': 'r', 'x-slack-unique-id': 'Y9d_88JaQxY3QqL2-OT0EgAAoAY', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'x-robots-tag': 'noindex,nofollow', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'x-slack-req-id': '2abd198778eea9cf37f95ec7f6743659', 'vary': 'Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '156', 'x-backend': 'main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-siez', 'x-slack-shared-secret-outcome': 'no-match', 'via': 'envoy-www-iad-sktt, envoy-edge-nrt-9q31', 'x-edge-backend': 'envoy-www', 'x-slack-edge-shared-secret-outcome': 'no-match', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {"ok":false,"error":"account_inactive"}
Traceback (most recent call last):
  File "/Users/kimhuiji/Desktop/Seek_Crolling/seek/crawl/seek_crawl.py", line 136, in <module>
    Msg_bot(eia[0], eia[1], eia[2], eia[3], eia[5], eia[6])
  File "/Users/kimhuiji/Desktop/Seek_Crolling/seek/crawl/seek_crawl.py", line 20, in Msg_bot
    client.chat_postMessage(
  File "/Users/kimhuiji/Library/Python/3.9/lib/python/site-packages/slack_sdk/web/client.py", line 2072, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/Users/kimhuiji/Library/Python/3.9/lib/python/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/kimhuiji/Library/Python/3.9/lib/python/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/Users/kimhuiji/Library/Python/3.9/lib/python/site-packages/slack_sdk/web/base_client.py", line 309, in _urllib_api_call
    return SlackResponse(
  File "/Users/kimhuiji/Library/Python/3.9/lib/python/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'account_inactive'}

**Comment by Arc1el** [comment]
You need to put a block in the text argument of the payload.

**Comment by huiji072** [comment]
token 만료 문제

참고 : https://wooiljeong.github.io/python/slack-bot/#:~:text=Python%EC%9C%BC%EB%A1%9C%20%EC%8A%AC%EB%9E%99%EB%B4%87%20%EB%A7%8C%EB%93%A4%EA%B8%B0,-Python%EA%B3%BC%20Slack&text=%EB%A8%BC%EC%A0%80%2C%20Slack%20API%20%ED%8E%98%EC%9D%B4%EC%A7%80%EC%97%90%EC%84%9C,Bot%20%EA%B3%84%EC%A0%95%EC%9D%84%20%EC%B4%88%EB%8C%80%ED%95%A9%EB%8B%88%EB%8B%A4.
